### ISSUE TITLE
CSS vars set in the style attribute via JS appears to not be preserved.

### ISSUE THREAD

**Issue by Ampflower** [LadybirdBrowser/ladybird#1712]
Relevant section of code:

https://github.com/Ampflower/ampflower.gay/blob/951fbd1e764a14e767070c9903ea7e017d1a3de4/src/assets/js/hibiscus.js#L63-L66

It is notable that inspect element can override it and preserve it perfectly fine, telling me this is likely a JS API problem and not a CSS or DOM problem.

**Comment by AtkinsSJ** [comment]
I think this is the relevant code:

https://github.com/LadybirdBrowser/ladybird/blob/e40ad73ae79023f64e250f854d0730c21e0f54fc/Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp#L291-L297

CSS variables (technical term "custom properties") will return nothing from `property_id_from_string()` so it's not doing anything.

A rough idea of what needs changing:
- Checks there for a custom property name, and probably pass an `Optional<FlyString> custom_property_name` to the other `set_property()` method.
- `PropertyOwningCSSStyleDeclaration::set_a_css_declaration()` also needs to take the custom property name, and store it in `m_custom_properties` instead of `m_properties`.

**Comment by ankushChatterjee** [comment]
Created a PR: #1978 for this.

**Comment by Ampflower** [comment]
#2460 (the successor to #1978) is merged and seems like it should've closed this.
