### ISSUE TITLE
Meta: Pre-commit CI scripts don't work with system /bin/bash on macOS

### ISSUE THREAD

**Issue by ADKaster** [LadybirdBrowser/ladybird#283]
macOS ships Bash 3.2 by default. Our `#!/usr/bin/env bash` scripts for pre-commit CI use bash-isms from after that release.

For example, `check-debug-flags.sh`

```
Meta/check-debug-flags.sh: line 39: bad substitution: no closing `)' in <(
    if [ "$#" -eq "0" ]; then
        git ls-files --             '*.cpp'             '*.h'             '*.in'
    else
        # We're in the middle of a pre-commit run, so we should only check the files that have
        # actually changed. The reason is that "git ls-files | grep" on the entire repo takes
        # about 100ms. That is perfectly fine during a CI run, but becomes noticeable during a
        # pre-commit hook. It is unnecessary to check the entire repository on every single
        # commit, so we save some time here.
        for file in "$@"; do
            if [[ ("${file}" =~ \.cpp || "${file}" =~ \.h || "${file}" =~ \.in) ]]; then
                echo "$file"
            fi
        done
    fi     | xargs grep -E '(_DEBUG|DEBUG_)'     | sed -re 's,^.*[^a-zA-Z0-9_]([a-zA-Z0-9_]*DEBUG[a-zA-Z0-9_]*).*$,\1,'     | sort -u
)
[FAIL]: Meta/check-debug-flags.sh
```

We don't specify homebrew bash as a requirement in our build instructions.

So, we should do one of three things:

1) require brew bash for contributors
2) port the scripts to older bash/POSIX sh/zsh/etc
3) rewrite problematic scripts in a more maintainable language, like python3

**Comment by sideshowbarker** [comment]
> 3\. rewrite problematic scripts in a more maintainable language, like python3

From what I’ve seen of the scripts so far:

* I note that they’re all quite short, less than 75 lines — and mostly less than 50 lines, and some only ~20–30 lines
* the code is straightforward, relatively uncomplicated and seems pretty easily maintainable already in its current form

So to me at least it seems like there are no specific concrete problems that would solved by rewriting them in python at this point — any benefits of doing it don’t seem like they’d be significant enough to justify the costs.

(That said, I’ll admit to some personal bias in favor of the idea that things which are simple and straightforward enough to be done in bash _should_ be done in bash rather than in python or whatever else.)
