### ISSUE TITLE
Skia is not portable

### ISSUE THREAD

**Issue by theoparis** [LadybirdBrowser/ladybird#451]
Requiring skia means ladybird will not work on BSD systems 😕 

See this skia bug report for example https://issues.skia.org/issues/40045542, it just got closed as wont fix. It is unfortunate to see yet another browser following the route of being non-portable...

**Comment by diath** [comment]
> It is unfortunate to see yet another browser following the route of being non-portable...

It kind of sounds like you're accusing people of making a deliberate choice to exclude FreeBSD which is not the case but rather a side effects of utilizing a library that doesn't support FreeBSD out of the box. Currently, certain platforms (such as FreeBSD and Windows) are not considered a priority as the software is still in its early stages (and partially due to lack of active contributors willing to commit time and resources to these said platforms) but that does not mean that long-term the project wants to exclude these platforms, especially that the issue you linked provides a Skia patch that adds FreeBSD support, and Ladybird uses vcpkg for installing the required libraries, which supports custom patches to the libraries you build, so it's not like it wouldn't be possible to, later in the future, integrate such a patch to the Skia build step - hell, if you have any interest in actively maintaining FreeBSD support for Ladybird, you could be the person adding such support and submitting a PR.

**Comment by awesomekling** [comment]
While I sympathize with this problem, our main target platforms at the moment are Linux and macOS. Bringing Skia to every other platform is far outside the scope of the Ladybird project.

I see that BSD systems still manage to run Chromium (FreeBSD has a `www/chromium` port for example), so it's clearly portable, even if it requires extra steps from OS/distro packagers.
