### ISSUE TITLE
Scrollbars appear unnecessarily with overflow: scroll

### ISSUE THREAD

**Issue by defyentropy** [LadybirdBrowser/ladybird#829]
When the `overflow: scroll` property is added to an element, vertical and horizontal scrollbars appear even when the element's content does not overflow. If `overflow-x` or `overflow-y` are used individually, only the respective scrollbars appear.

Test Page:
```html
<!DOCTYPE html>
<html>
    <head>
        <style>
            .test {
                overflow: scroll;
                background: #dedede;
                padding: 2em;
            }
        </style>
    </head>

    <body>
        <div class="test">
            These scrollbars shouldn't be here!
        </div>
    </body>

</html>
```
Screenshot::
![screenshot-2024-07-25-18-06-44](https://github.com/user-attachments/assets/c76fec48-90fc-447c-93a4-1ee3cafa851e)

Expected Behavior:
The scrollbars should not be there if there is no overflow.

**Comment by AtkinsSJ** [comment]
:thinking: Showing the scrollbars is correct. The [spec](https://www.w3.org/TR/css-overflow-3/#valdef-overflow-scroll) says for `scroll`:

> if the user agent uses a scrolling mechanism that is visible on the screen (such as a scroll bar or a panner), that mechanism should be displayed whether or not any of its content is clipped. This avoids any problem with scrollbars appearing and disappearing in a dynamic environment.

In fact, Chrome does show scrollbars:
![image](https://github.com/user-attachments/assets/a8061b9c-7108-4485-8f3b-5cb4184675e5)

Firefox doesn't, but I think that's just because their scrollbar tracks are not visible even when there is a scrollbar.
